account_id = "1c256d3ed81a2a8fd7473a7ca6cae980"
compatibility_date = "2022-04-23"
entry-point = "build"
name = "remixcloudflare"
type = "javascript"
workers_dev = true

kv_namespaces = [
  {binding = "remixcloudflare", id = "a1713ffb5bc4437b9236888ee8688d09"},
]
